### ISSUE TITLE
Loss of provisioned k8s template resources [because of Garbage Collection] after k8s node reload event

### ISSUE THREAD

**Issue by joshisa** [couchbase/service-broker#73]
**Describe the bug**
On our managed K8s/OpenShift environment within IBM Cloud, I have encountered a sudden collective loss of all provisioned K8s resources that were instantiated via my deployed service broker which is running 3 replicas (HA) on different nodes.  I had 4-5 different templated workloads across 4-5 different namespaces that were all affected simultaneously.  Their only common attribute was that they were "provisioned" by the service-broker.  I don't know where to attribute the cause (yet), but deeper investigation into K8s events shows that after a consistent period of time (~ 5-7 hrs), the managed K8s cluster experiences a cluster update (don't through IBM Cloud internal processes most likely).  This update/reload doesn't last longer than 1-2 mins. 
![image](https://user-images.githubusercontent.com/1133849/115127799-71a62200-9fa7-11eb-837f-2fe39cdebe24.png)

Nodes are reloaded ...
![image](https://user-images.githubusercontent.com/1133849/115127834-c5187000-9fa7-11eb-8ebe-9abad3152158.png)

Interestingly (coincidentally?) - subsequent to this cluster/node reload activity, I then see `Stopping container [foo]` messages triggered.  I had turned up stderr log levels on the broker, however I only see normal map refreshes, broker config reloads with valid statements and the triggered deletion activity via HTTP DELETE.  

![image](https://user-images.githubusercontent.com/1133849/115148248-b58f3a80-a02c-11eb-9917-9baff0f21320.png)
  
I believe this is specific to IBM Cloud managed K8s/OpenShift because I have not experienced the same thing in AWS/Azure so far.

**To Reproduce**
1. Deploy the broker onto IBM Cloud
2. Provision any type of resource via the broker and wait for a node reload event
3. Watch within respective namespaces for deployed K8s resources (deploy/statefulset/pods/config maps/secrets/ etc ....).  
4. Notice K8s resources are deleted and no longer present. 

**Expected behavior**
Provisioned k8s resources shouldn't become deleted by cluster/node reloads/restarts/updates.

**Workaround**
Unsure.  One thought was to remove the delete verb from the broker's clusterrole ... but that degrades the end-to-end experience of managing a provisioned service and would result in runaway resource consumption.

**Environment (please complete the following information):**
 - Kubernetes Version: OpenShift 4.6 on IBM Cloud
 - Service Broker Version : Latest code base

**Additional context**
As mentioned above, I'm still trying to identify the exact trigger for this behavior ... but I'm suspicious that it is related to the broker getting triggered inadvertently in some way because of the broad impact across all k8s resources related to the broker and not to other resources deployed manually.  I will share more info as I find it ... but welcome thoughts on what might be happening from others who understand the deletion lifecycle and under what circumstances this could occur and how to prevent or make it less likely.

**Comment by spjmurray** [comment]
SB will only delete when told to, and (I suspect this is all in the docs) we only delete the service intsnace registry, which is a secret.
Any resources associated with a service instance should be owned by the registry, and will be garbage collected by Kubernetes. 
Does this fit with your observations? 

Sent from Yahoo Mail on Android 
 
  On Sun, 18 Apr 2021 at 15:11, Sanjay ***@***.***> wrote:   


Describe the bug
On our managed K8s/OpenShift environment within IBM Cloud, I have encountered a sudden collective loss of all provisioned K8s resources that were instantiated via my deployed service broker which is running 3 replicas (HA) on different nodes. I had 4-5 different templated workloads across 4-5 different namespaces that were all affected simultaneously. Their only common attribute was that they were "provisioned" by the service-broker. I don't know where to attribute the cause (yet), but deeper investigation into K8s events shows that after a consistent period of time (~ 5-7 hrs), the managed K8s cluster experiences a cluster update (don't through IBM Cloud internal processes most likely). This update/reload doesn't last longer than 1-2 mins.


Nodes are reloaded ...


Interestingly (coincidentally?) - subsequent to this cluster/node reload activity, I then see Stopping container [foo] messages triggered. I had turned up stderr log levels on the broker, however I only see normal map refreshes, broker config reloads with valid statements and the triggered deletion activity via HTTP DELETE.



I believe this is specific to IBM Cloud managed K8s/OpenShift because I have not experienced the same thing in AWS/Azure so far.

To Reproduce
Steps to reproduce the behavior:
   
   - Deploy the broker onto IBM Cloud
   - Provision any type of resource via the broker and wait for a node reload event
   - Watch within respective namespaces for deployed K8s resources (deploy/statefulset/pods/config maps/secrets/ etc ....).
   - Notice K8s resources are deleted and no longer present.

Expected behavior
Provisioned k8s resources shouldn't become deleted by cluster/node reloads/restarts/updates.

Workaround
Unsure. One thought was to remove the delete verb from the broker's clusterrole ... but that degrades the end-to-end experience of managing a provisioned service and would result in runaway resource consumption.

Environment (please complete the following information):
   
   - Kubernetes Version: OpenShift 4.6 on IBM Cloud
   - Service Broker Version : Latest code base

Additional context
As mentioned above, I'm still trying to identify the exact trigger for this behavior ... but I'm suspicious that it is related to the broker getting triggered inadvertently in some way because of the broad impact across all k8s resources related to the broker and not to other resources deployed manually. I will share more info as I find it ... but welcome thoughts on what might be happening from others who understand the deletion lifecycle and under what circumstances this could occur and how to prevent or make it less likely.

**Comment by joshisa** [comment]
@spjmurray Your description matches what I'm seeing.  I think I know what's going on now.
#### AS-IS:
1.  Broker lives in namespace `foo`.  I've given it a clusterrole and clusterbinding to allow manipulation across namespaces.  I also registered the configurations for all of the different services in one file within the same `foo` namespace.
2. My config defines resources in namespace `bar` amongst a few others.

#### Root Cause Analysis:
Because of the above setup, my provisioned registry secrets are all being created within namespace `foo`.  I see all of them populated and present.  However, the provisioned resources live in `bar` and have an ownerReference to the secret which lives in `foo`.  The [doc](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/) is pretty clear that `Cross-namespace owner references are disallowed by design.` and I'm violating that.  Therefore, when the K8s control-plane reloads/refreshes ... garbage collection is occurring on these "rogue" resources with an ownerReference that cannot be located.

#### Next Steps:
After looking through the code, it seems to me that if I break apart my configuration definition into a per-namespace set of configs - then I will cause the "owning" secret to be provisioned in `bar` and live happily alongside any provisioned `bar` resources .  With the broker having a broader clusterrole view of configurations across the cluster, it should have appropriate list/watch visibility into the config within namespace `bar`.  This should allow the K8s cluster to identify the ownerReference resource (registry secret) and avoid garbage collection.   Am I on the right track?

As an alternative, I could also consider deploying separate brokers and configs per-namespace and limiting their ACL to Role but that seems inefficient and unnecessary.  It would also force users to register multiple broker routes.

**Comment by spjmurray** [comment]
How about I add a parameter to the configuration binding that allows you to choose the namespace a registry is provisioned in (/looked for the SB)?  Then you can either a) hard code it b) impicitly use the namespace of the SB c) implicitly use the namespace of the service instance.  Let me have a play, I should get it released today if it looks good!

**Comment by joshisa** [comment]
@spjmurray That sounds really great.  I'll be happy to test and share feedback as well.

**Comment by joshisa** [comment]
@spjmurray - I grabbed the branch, built a binary and new image to test.  After updating my config with `registryScope` using a value of `Explicit` and declaring `registryNamespace` with a specific namespace of interest, things looked great!  I could see the registry secret being created in the appropriate namespace and deleted when I gestured to do so. Owned resources were GC'd correctly when the secret was removed.  I'll deploy a few services on my cloud env and let them sit.  In the past, I would lose them to the inadvertent GC within 1/2 - 1 day.  I don't think this will happen now.  Will post my findings here.  Thanks for the amazing responsiveness to feedback/inquiries and this project in general.  It's a really flexible, well-designed approach to connecting the open-service broker concept with K8s resources.   Kudos to you and the team.

**Comment by spjmurray** [comment]
@joshisa who needs automated testing huh?  Good to know it appears to work so far.  This certainly isn't the final code, I think an instance ID -> namespace mapping for the directory is too inflexible.  Probably going to change this to a JSON document so we can add/remove stuff at will in the future as needs arise.

This whole project was designed to show case best-in-breed development processes, super fast fixes, testing and releases, glad you approve!  And _we_ are the team, it's a community effort because I couldn't do this all on my own, so thanks to you!
